/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as AyudasRouteImport } from './routes/ayudas'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculadorasIndexRouteImport } from './routes/calculadoras.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CalculadorasSlugRouteImport } from './routes/calculadoras.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudasRoute = AyudasRouteImport.update({
  id: '/ayudas',
  path: '/ayudas',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasIndexRoute = CalculadorasIndexRouteImport.update({
  id: '/calculadoras/',
  path: '/calculadoras/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasSlugRoute = CalculadorasSlugRouteImport.update({
  id: '/calculadoras/$slug',
  path: '/calculadoras/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/ayudas': typeof AyudasRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculadoras/$slug': typeof CalculadorasSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/calculadoras/': typeof CalculadorasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/ayudas': typeof AyudasRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculadoras/$slug': typeof CalculadorasSlugRoute
  '/blog': typeof BlogIndexRoute
  '/calculadoras': typeof CalculadorasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/ayudas': typeof AyudasRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculadoras/$slug': typeof CalculadorasSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/calculadoras/': typeof CalculadorasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/ayudas'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/quienes-somos'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/calculadoras/$slug'
    | '/blog/'
    | '/calculadoras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/ayudas'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/quienes-somos'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/calculadoras/$slug'
    | '/blog'
    | '/calculadoras'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/ayudas'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/quienes-somos'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/calculadoras/$slug'
    | '/blog/'
    | '/calculadoras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  AyudasRoute: typeof AyudasRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CalculadorasSlugRoute: typeof CalculadorasSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CalculadorasIndexRoute: typeof CalculadorasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayudas': {
      id: '/ayudas'
      path: '/ayudas'
      fullPath: '/ayudas'
      preLoaderRoute: typeof AyudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/': {
      id: '/calculadoras/'
      path: '/calculadoras'
      fullPath: '/calculadoras/'
      preLoaderRoute: typeof CalculadorasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/$slug': {
      id: '/calculadoras/$slug'
      path: '/calculadoras/$slug'
      fullPath: '/calculadoras/$slug'
      preLoaderRoute: typeof CalculadorasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  AyudasRoute: AyudasRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  CalculadorasSlugRoute: CalculadorasSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CalculadorasIndexRoute: CalculadorasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
